### ISSUE TITLE
adding addTargetToExternalLinks in plugins.js

### ISSUE THREAD

**Issue by jstam89** [nshenderov/strapi-plugin-ckeditor#10]
Hi!

I would like my links to open in a new tab and I found some documentation about this in the [docs](https://ckeditor.com/docs/ckeditor5/latest/features/link.html)

Now I've implemented this but probably the wrong way, can anyone help? My plugins.js looks as follows:

```
module.exports = ({env}) => ({
    'transformer'         : {
        enabled: true,
        config : {
            prefix            : '/api/',
            responseTransforms: {
                removeAttributesKey: true,
                removeDataKey      : true,
            }
        }
    },
    'seo'                 : {
        enabled: true,
    },
    'measurement-protocol': {
        config: {
            apiSecret          : 'LUGGNONmQVW5U0ZrlK6AxQ',
            measurementId      : 'G-JKZ4XHRX11',
            useValidationServer: false,
        }
    },
    'ckeditor'            : {
        enabled: true,
        plugins: {
            strapiTheme: false,
        },
        editor : {
            link: {
                decorators: {
                    addTargetToExternalLinks: {
                        mode      : 'automatic',
                        attributes: {
                            target: '_blank',
                            rel   : 'noopener noreferrer'
                        }
                    }
                }
            }
        }
    }
});
```

**Comment by tardencilladamian** [comment]
Hi, this code works correctly, strapi v4.

`
link: {
          addTargetToExternalLinks: true,
          decorators: {
            openInNewTab: {
              mode: "manual",
              label: "Open in a new tab",
              defaultValue: true,
              attributes: {
                target: "_blank",
                rel: "noopener noreferrer",
              },
            },
          },
        },
`

**Comment by jstam89** [comment]
> Hi, this code works correctly, strapi v4.
> 
> ```
> link: {
>     addTargetToExternalLinks: true,
>     decorators: {
>     openInNewTab: {
>         mode: "manual",
>         label: "Open in a new tab",
>         defaultValue: true,
>             attributes: {
>                 target: "_blank",
>                 rel: "noopener noreferrer",
>             },
>         },
>     },
> },
> ```

Nope still not working :(

**Comment by tardencilladamian** [comment]
> > Hi, this code works correctly, strapi v4.
> > ```
> > link: {
> >     addTargetToExternalLinks: true,
> >     decorators: {
> >     openInNewTab: {
> >         mode: "manual",
> >         label: "Open in a new tab",
> >         defaultValue: true,
> >             attributes: {
> >                 target: "_blank",
> >                 rel: "noopener noreferrer",
> >             },
> >         },
> >     },
> > },
> > ```
> 
> Nope still not working :(

It worked for me, this is my editor.

![Editor](https://i.ibb.co/HDMFr8v/Screen-Shot-2022-06-03-at-06-54-03.png)

**Comment by jstam89** [comment]
I'm using the CKEditor 5

**Comment by tardencilladamian** [comment]
> I'm using the CKEditor 5

Me too. Strapi v4.1.12 & CKEditor 5

**Comment by jstam89** [comment]
> > I'm using the CKEditor 5
> 
> Me too. Strapi v4.1.12 & CKEditor 5

mine looks more like the editor in the docs, can you share your plugin config with me?

**Comment by tardencilladamian** [comment]
> > > I'm using the CKEditor 5
> > 
> > 
> > Me too. Strapi v4.1.12 & CKEditor 5
> 
> mine looks more like the editor in the docs, can you share your plugin config with me?

```
ckeditor: {
    enabled: true,
    config: {
      plugin: {},
      editor: {
        removePlugins: ["Markdown"],
        toolbar: {
          items: [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "removeFormat",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "alignment",
            "|",
            "StrapiMediaLib",
            "link",
            "|",
            "undo",
            "redo",
            "|",
            "sourceEditing",
          ],
        },
        link: {
          addTargetToExternalLinks: true,
          decorators: {
            openInNewTab: {
              mode: "manual",
              label: "Open in a new tab",
              defaultValue: true,
              attributes: {
                target: "_blank",
                rel: "noopener noreferrer",
              },
            },
          },
        },
        heading: {
          options: [
            {
              model: "paragraph",
              title: "Paragraph",
              class: "paragraph",
            },
            {
              model: "heading2",
              view: "h2",
              title: "Heading 2",
              class: "h2",
            },
            {
              model: "heading3",
              view: "h3",
              title: "Heading 3",
              class: "h3",
            },
            {
              model: "heading4",
              view: "h4",
              title: "Heading 4",
              class: "h4",
            },
            {
              model: "heading5",
              view: "h5",
              title: "Heading 5",
              class: "h5",
            },
            {
              model: "heading6",
              view: "h6",
              title: "Heading 6",
              class: "h6",
            },
          ],
        },
      },
    },
  },
```

**Comment by jstam89** [comment]
You sir are amazing! This did the trick and it looks way better now :D made my day!
