### ISSUE TITLE
CKeditor5 does not replace default Strapi editor

### ISSUE THREAD

**Issue by webkwondo** [nshenderov/strapi-plugin-ckeditor#105]
In the plugin description it says that "CKEditor 5 replaces the default Strapi WYSIWYG editor with a customized build..." however it doesn't do this. The default Strapi editor for Rich text stays where it was. The plugin adds a custom field - and in order to use this plugin you need to replace all your Rich text fields in all your collections with this custom field. I spent a day trying to figure this out, because other editors that I tried for Strapi actually replaced the default editor.

This issue is also related to this topic on Strapi Forum: https://forum.strapi.io/t/ckeditor5-is-not-replacing-my-default-strapi-editor/27310

Thank you.

**Comment by lamuertepeluda** [comment]
The [docs](https://github.com/nshenderov/strapi-plugin-ckeditor#%EF%B8%8F-configuration) says it's based on custom fields, though... so maybe this issue is more about the description rather with how the plugin works.

**Comment by arnoldski** [comment]
@webkwondo, see solution on https://github.com/nshenderov/strapi-plugin-ckeditor/issues/80#issuecomment-1455390886

**Comment by alexelker** [comment]
The plugin worked better when it replaced the default WYSIWYG. @webkwondo, just go back to version 1.1.3
