### ISSUE TITLE
Centered image doesn't get a class applied 

### ISSUE THREAD

**Issue by stijnwesterhof** [nshenderov/strapi-plugin-ckeditor#11]
It seems that when I want to center an image there isn't any class added to the image.
It does work for the alignment to the right or resizing of the image.
![image](https://user-images.githubusercontent.com/15048777/172841867-7fd759a3-8ad5-4ceb-aa46-52e8066bd492.png)

I'm using the default configuration. 

Please let me know if you need anymore information.

Edit:
I noticed that class: `image` acts as the 'centered class', but I don't think that's desired behavior. `image-style-center` would be a better classname imo.

I managed to center the images with this css though:
```
.image-style-side{
    margin-left: auto;
    margin-right: 0 !important
}

.image {
    margin: 0 auto;
}

**Comment by nshenderov** [comment]
@stijnwesterhof Read the documentation https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html
