### ISSUE TITLE
Scope starts with '.' or '_': _sh

### ISSUE THREAD

**Issue by MahmoodKamali** [nshenderov/strapi-plugin-ckeditor#111]
There is an issue with the package naming as it started with `_` which is against npm standard naming. When npm or yarn tries to download the package, it returns error 400 as follows:

```
npm ERR! code E400
npm ERR! 400 Bad Request - GET https://www.npmjs.com/package/npm-proxy/@_sh%2fstrapi-plugin-ckeditor - Scope starts with '.' or '_': _sh
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2023-07-03T06_37_34_142Z-debug-0.log
ERROR: Job failed: exit status 1
````
I had to manually download the package and rename the file as well as the package.json values.

**Comment by hrahimi270** [comment]
@MahmoodKamali I had the same issue when I was using a custom npm proxy.
