### ISSUE TITLE
It will be good to have a custom element support

### ISSUE THREAD

**Issue by Kalgros20** [nshenderov/strapi-plugin-ckeditor#119]
I'm a little bit frustrated, because it seems that we dont have a way to add a custom element, in the CMS. Thinking in user exp, i want to add custom classes to a `<p>` or any heading tag, and the user dont need to know what will be added. Because in front-end i want to have a bunch classes that will be used.... The CMS will be managed by people that dont know much html, and in thoses cases.. when more abstraction, i think will be better.... Aside, good repo and stuff. <3

**Describe the solution you'd like**
Could be possible to use this feature of custom elements.

 [Ref](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#enabling-custom-elements)

**Comment by mikegazdag** [comment]
I'm not sure what you mean, via the editorConfig options your able to add somewhat custom styles and elements. Here, I'm adding custom header elements that mostly output Tailwind classes.

```
/* CKEditor configuration */
configs: {
  custom: {
    editorConfig:{
      heading: {
        options: [
          { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ds--h1' },
          { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ds--h2' },
          { model: 'heading3', view: 'h1', title: 'Display 1', class: 'ds--d1' },
          { model: 'heading4', view: 'h2', title: 'Display 2', class: 'ds--d2' },
          { model: 'heading5', view: 'p', title: 'Body', class: 'ds--d2' },
          { model: 'heading6', view: 'p', title: 'Body - Medium', class: 'ds--d2 ds--medium' },
          { model: 'heading7', view: 'p', title: 'Body Alt', class: 'ds--d2' },
        ]
      }
    }
  }
}

```

**Comment by Benman2005** [comment]
Hi, not sure if it's worth asking. The OP had a bit of a different question, but i'd like to still be able to add a custom html element inside my ckeditor. 
The problem now is that when editing source it actually accepts the custom html element and saves it. It just doesnt show it outside of the source editor, so in the normal editor. 
I did allow all elements in the editorConfig, but according to [ckeditor documentation](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#enabling-custom-elements) i would need to register the custom element  in the DataSchema, but I have no idea where in this strapi implementation i would have to declare these. 
Is it possible? It can just show as regular text, as long as it shows and is <custom-element> in the html source.
@nshenderov can you help me with this? oh yeah i'm on v5 right now
