### ISSUE TITLE
Updated strapi version and loose toolbar items customization

### ISSUE THREAD

**Issue by dieegomr** [nshenderov/strapi-plugin-ckeditor#121]
I have noticed a change in the toolbar items, specifically in the context of customizing text. In the older version, I had a set of toolbar items like this:

![Captura de Tela 2023-10-13 às 10 43 23 AM](
https://github.com/nshenderov/strapi-plugin-ckeditor/assets/103800665/3103ca61-0834-4ee5-bc73-b40ee196dac9)

However, in the latest version, the toolbar items have changed.

![Captura de Tela 2023-10-13 às 10 52 47 AM](
https://github.com/nshenderov/strapi-plugin-ckeditor/assets/103800665/6961d8eb-006f-4356-9659-831ce9fb0ba0)

I would not like to have to replace all of my rich text by a custom ckeditor as they did here:
https://github.com/nshenderov/strapi-plugin-ckeditor/issues/80#issuecomment-1455390886

Is it possible to keep it like it was before?

**Comment by LucaNerlich** [comment]
Where and how did you configure your toolbar? With version 2.x you'will need a 'config.txt' in `strapiRoot/config/ckeditor.txt`.

**Comment by fabiennecornel** [comment]
@dieegomr check my answer here https://github.com/nshenderov/strapi-plugin-ckeditor/issues/127
