### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Markdown')

### ISSUE THREAD

**Issue by thunt4jr** [nshenderov/strapi-plugin-ckeditor#122]
**Describe the bug**
main.e5a400d1.js:4737 TypeError: Cannot destructure property 'icon' of 's.get(...)' as it is undefined.

Uncaught TypeError: Cannot read properties of undefined (reading 'Markdown')

**To Reproduce**
1. Go to 'open up event's component and try to add a new event that has custom ckeditor. It will just give me lazy loading and spin non-stop.  '

**Expected behavior**
Everything will go blank or white screen

**Screenshots**

![image](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/13003749/2325e181-71c2-4867-b743-29f877602464)

**please complete the following information:**
 - plugins.js (if exist)
 - package.json
 - "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@ckeditor/ckeditor5-markdown-gfm": "^40.0.0",
    "@strapi/plugin-i18n": "4.15.2",
    "@strapi/plugin-seo": "^1.9.6",
    "@strapi/plugin-users-permissions": "4.15.2",
    "@strapi/provider-email-amazon-ses": "^4.15.2",
    "@strapi/provider-upload-aws-s3": "^4.15.2",
    "@strapi/strapi": "4.15.2",
    "better-sqlite3": "9.1.1",
    "pg": "^8.11.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.3.4",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-sitemap": "^3.0.6",
    "styled-components": "^5.3.11"
  },
 - node version
 - 20.9.0

**Additional context**

**Comment by EmilianoTalamo** [comment]
There seems to be an issue with newer strapi versions, where the current method of importing packages within the app file seems to have changed or it's not working.

**Comment by thunt4jr** [comment]
This has been resolved. The issues was inside the ckeditor.txt. 

Not sure how this was added but this was causing the issues. 

`CKEditor5.markdownGfm.Markdown,`

**Comment by EmilianoTalamo** [comment]
I wouldn't call it solved yet because the import of third party plugins for ckeditor (like the one you're mentioning, markdownGfm) is not working.

That plugin is required to output the custom field as markdown. Someone on your project added it because it's also listed as a dependency on your `package.json`.

**Comment by maxdenaro** [comment]
Hi! I get exactly the same error. Please tell me how to solve the problem? I do everything exactly with the documentation
