### ISSUE TITLE
Wrong URL when using Images in CK Editor, when deploying Strapi Instance

### ISSUE THREAD

**Issue by exotexot** [nshenderov/strapi-plugin-ckeditor#124]
I want to know how you guys manage inline images in the CKEDitor when you deploy them to another server.
As I use strapi in docker, I usually prepare my content locally and then move everything to my server.

When I have inline images in the CK Editor, all the images will be prefixed with the absolute URL (e.g. localhost:1337).
Then when I transfer the contents of my database and uploads folder, those references will be broken of course.

How to handle this scenario?

**Comment by cungkriink** [comment]
I have the same problem and haven't found a solution

**Comment by Gr33nW33n** [comment]
Hello @exotexot & @cungkriink,

do you have a solution for this?

BR Jakob

**Comment by exotexot** [comment]
@Gr33nW33n in my frontend i just manually prefix url with the host address i need

**Comment by yinhx3** [comment]
Media field doesn't use URL prefix, CKEditor should align with build-in behavior

For example:
get `/api/articles?populate=*`
```json
      "cover": {
        "id": 4,
        "documentId": "tvudk0hh4ds45rnxslkoreeo",
        "name": "coffee-art",
        "alternativeText": "An image uploaded to Strapi called coffee-art",
        "caption": "coffee-art",
        "width": 5824,
        "height": 3259,
        "formats": {
          "thumbnail": {
            "name": "thumbnail_coffee-art",
            "hash": "thumbnail_coffee_art_aa2ebd657b",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "path": null,
            "width": 245,
            "height": 137,
            "size": 5.86,
            "sizeInBytes": 5860,
            "url": "/uploads/thumbnail_coffee_art_aa2ebd657b.jpeg"
          },
        },
        "hash": "coffee_art_aa2ebd657b",
        "ext": ".jpeg",
        "mime": "image/jpeg",
        "size": 978.11,
        "url": "/uploads/coffee_art_aa2ebd657b.jpeg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-03-07T09:25:45.228Z",
        "updatedAt": "2025-03-07T09:25:45.228Z",
        "publishedAt": "2025-03-07T09:25:45.228Z"
      }

**Comment by nshenderov** [comment]
For local media, I would recommend using Strapi components. This allows for more precise processing on the frontend. The HTML string output of the wysiwyg editor is meant to be used as is, without parsing. This means that once you add an image to the editor and save the output to the database, it becomes static and cannot dynamically adjust the URL.

There is a `url` option available in `config/server.js`, where you can specify the url you need. https://docs.strapi.io/dev-docs/configurations/server#available-options. However, I doubt it will be helpful in this scenario.

@yinhx3 The plugin behaves the same way as Strapi's default wysiwyg editor https://github.com/strapi/strapi/blob/8ca39da55ef0e9443e56f1ca9ea0d705a5e99f07/packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Wysiwyg/Field.tsx#L46
