### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by caenderl** [nshenderov/strapi-plugin-ckeditor#125]
Because node 20 is LTS, would it be possible to set the engine in package.json to 20?
Not sure if there's any other dependency that prevents from upgrading node version.

Thanks for this create plugin and the support :-)

**Comment by artanisdesign** [comment]
+1

**Comment by red-made** [comment]
+1

**Comment by sal1ner0** [comment]
+1

**Comment by knxroot** [comment]
+1

**Comment by Arunjenson** [comment]
+1
