### ISSUE TITLE
How can I customize the css class for the rendered img tag? Currently I'm adding it manually

### ISSUE THREAD

**Issue by doits930** [nshenderov/strapi-plugin-ckeditor#126]
I want when I upload an  images in the CKEDitor, in the img tag of that image, I can configure the css class.

This is how I manually configured the css class for the img tag
![image](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/130958432/a7f4493a-4442-4f70-9c8a-7fa8c0f50d6b)

How to handle this scenario?

**Comment by LucaNerlich** [comment]
I dont think that this is possible ootb. You will need to fork it and _hack_ that into the ckeditor yourself.
