### ISSUE TITLE
Changes made on source editing is not saved.

### ISSUE THREAD

**Issue by BashisthaSudeep** [nshenderov/strapi-plugin-ckeditor#130]
I've added `@ckeditor/ckeditor5-source-editing` plugin to allow me to add some id in the content inside CK editor. These ids are used  as the anchors in my frontend app.

When I update the HTML from the source editor, the update button isn't active. Even if I force update the content by changing other fields, the changes made in the source editor is lost.

Is this something intentional in CK editor? I don't think it is. And is this the correct repo to discuss this issue?

https://github.com/nshenderov/strapi-plugin-ckeditor/assets/32100152/2423dc61-3ab1-4d67-ba43-a2b71b69dbed

**Comment by nshenderov** [comment]
Are you sure you didn’t mix up the repository? This one is @_sh/strapi-plugin-ckeditor not the @ckeditor/strapi-plugin-ckeditor.
The source-editing plugin is included by default, make sure that the HTML Support plugin is configured properly.
[Screencast from 28-02-24 20:24:33.webm](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/103522779/256c3aae-b211-455c-8da2-376375d52053)
