### ISSUE TITLE
when uploading a gif image, it does not play

### ISSUE THREAD

**Issue by IIACTbIPb** [nshenderov/strapi-plugin-ckeditor#133]
When inserting a gif image into CKEditor, it is displayed statically
![image](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/61131365/8241cb61-8ec9-456d-97b5-dd5df82b485d)

And if you go into SourceEditing mode, you will notice that the picture looks like this

`
<img src="https://cloud/gif-name.gif" alt="gif-name.gif" srcset="https://cloud/gif-name.gif 202w," sizes="100vw" width="undefined" height="undefined">
`

if you remove the attribute `srcset` and exit SourceEditing mode,  the gif image will be displayed correctly

is it possible to remove this attribute somehow?

**Comment by nshenderov** [comment]
This happens because strapi resizes the image and the resized one is not animated for some reason. This is not related to this plugin. You can disable responsive images to remove srcset.
