### ISSUE TITLE
config Link not working

### ISSUE THREAD

**Issue by mauro-montano** [nshenderov/strapi-plugin-ckeditor#139]
Hi everyone!

I have ckeditor5 installed with strapi v4 and this config by default:

![Screen Shot 2024-04-03 at 14 46 34](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/112961400/5f16025a-158b-483c-87e9-5f3b90ca28dc)

The problem is that always open the pages in a new tab no matter if you set `Open in new tab` to off, so i'm trying to change the config or adding a new button but no configuration works for me. I tried changing the `ckeditor.txt` or adding in `plugins.js` 

Does anyone know how to edit the config to edit the buttons or add a new button to open the url in the same tab?

**Comment by Arunjenson-ss** [comment]
for me all the links are opening in the same tab 
can anyone check this ??

**Comment by Arunjenson** [comment]
thanks @mauro-montano
