### ISSUE TITLE
Is it possible to add a new field in Media Embed funcionality?

### ISSUE THREAD

**Issue by mauro-montano** [nshenderov/strapi-plugin-ckeditor#141]
I have installed ckeditor5 as a plugin in Strapi and I would like to add a new field called `Custom Image URL` that I will use as a video overlay in my website:

![image](https://github.com/nshenderov/strapi-plugin-ckeditor/assets/112961400/f7051676-ad03-41df-93b6-543c6879339c)

I think it is not possible just by modifying the ckeditor.txt file. Is there any way to do this or to extend the plugin to implement this new field?

**Comment by nshenderov** [comment]
@mauro-montano Hi, you need to modify the media-embed plugin or create a new one, and you will need to modify this integration plugin locally. Anyway, it is not an easy task. Check out the CKEditor documentation on plugin creation.
