### ISSUE TITLE
ckeditor height

### ISSUE THREAD

**Issue by Arunjenson-ss** [nshenderov/strapi-plugin-ckeditor#144]
how to set the height of the ckeditor5 ?

**Comment by nshenderov** [comment]
[You can modify those styles](https://github.com/nshenderov/strapi-plugin-ckeditor/blob/2b2932ddebc0801cb4a1c50f484da471012b8dd7/admin/src/components/Input/CKEditor/theme/additional.js#L7C1-L12C4)

[Here in config file](https://github.com/nshenderov/strapi-plugin-ckeditor/blob/2b2932ddebc0801cb4a1c50f484da471012b8dd7/README.md?plain=1#L212C1-L219C6)
