### ISSUE TITLE
Strapi 5 supports 

### ISSUE THREAD

**Issue by reslear** [nshenderov/strapi-plugin-ckeditor#148]
1. `npm install @_sh/strapi-plugin-ckeditor --force`
2. `npm run build`

```log
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

RollupError: [commonjs--resolver] Expression expected in /node_modules/@_sh/strapi-plugin-ckeditor/admin/src/components/CKEditorIcon.js

14: const SvgIcon = () => (
15:   <svg
^
16:   width="68"
17:   height="64"
```

**Comment by hung-enzo** [comment]
+1

**Comment by hsnbsst** [comment]
+1

**Comment by stillhartkonzept** [comment]
@nshenderov do you have a roadmap to support strapi 5? Thanks.

**Comment by reslear** [comment]
@stillhartkonzept eta https://github.com/nshenderov/strapi-plugin-ckeditor/pull/157

also already support https://github.com/ckeditor/strapi-plugin-ckeditor

**Comment by nshenderov** [comment]
@stillhartkonzept I'll release the new version today
