### ISSUE TITLE
Table Rows and columns data is not properly formatted 

### ISSUE THREAD

**Issue by CharuGoyalS** [nshenderov/strapi-plugin-ckeditor#149]
1. create table data in creation portal with Max rows and columns
2. Publish the Article with table
Expected Result

Table text should be wrapped and cell size should be adapted to the text data.
Actual Results

The table data of text and images are not wrapped and is displayed in a unreadable format.

**Comment by nshenderov** [comment]
Can't reproduce, need better explanation.
