### ISSUE TITLE
editor is not allowing to upload other file formats like word, ppt, Text, Excel, Json etc. from media library

### ISSUE THREAD

**Issue by CharuGoyalS** [nshenderov/strapi-plugin-ckeditor#151]
editor is not allowing to upload other file formats like word, ppt, Text, Excel, Json etc. from media library

**Comment by nshenderov** [comment]
The plugin by default is not supposed to do so. If you need any special format, you can customize the plugin to your needs or open a feature or PR request.

**Comment by CharuGoyalS** [comment]
Please approve https://github.com/nshenderov/strapi-plugin-ckeditor/pull/153 for the same
