### ISSUE TITLE
Table properties and Cell properties are not showing up for table in CkEditor. 

### ISSUE THREAD

**Issue by CharuGoyalS** [nshenderov/strapi-plugin-ckeditor#154]
**Describe the bug**
Table properties and Cell properties are not showing up for table in Ckeditor. 

**To Reproduce**
1. Go to 'Rich text editor'
2. select a table and Click on table
3. The table properties and cell properties are not showing even though they are added in ckeditor.txt. 
<img width="824" alt="image" src="https://github.com/user-attachments/assets/e1a1c098-a687-4cac-8034-a1ff1409e40b">

**Expected behavior**

**Screenshots**

**please complete the following information:**
 - plugins.js (if exist)
 - package.json
 - node version

**Additional context**

**Comment by nshenderov** [comment]
I think you are doing something wrong. This is not the official CKEditor 5 repository but the plugin that integrates it into Strapi CMS.
![Screenshot from 2024-08-05 13-15-33](https://github.com/user-attachments/assets/26e29e9f-eb8c-4690-8603-3ebe672feb3d)
![Screenshot from 2024-08-05 13-16-30](https://github.com/user-attachments/assets/f0aa2aeb-b913-403e-b1e5-eebe93c3538d)
