### ISSUE TITLE
The video doesn't get attached in Rich text editor from media library.

### ISSUE THREAD

**Issue by CharuGoyalS** [nshenderov/strapi-plugin-ckeditor#155]
**Describe the bug**
The video doesn't get attached in Rich text editor from media library.

**To Reproduce**
1. Go to strapi media library from the rich text editor
2. try to attach a video file.
3. video file doesn't get attached in Rich text editor.

**Expected behavior**
Rich text editor video attachment should work.

**Comment by nshenderov** [comment]
@CharuGoyalS Can't reproduce
![Screenshot from 2024-08-07 12-28-47](https://github.com/user-attachments/assets/2742ed69-ad22-49c2-881d-d7f53a341271)
![Screenshot from 2024-08-07 12-28-55](https://github.com/user-attachments/assets/db731b2e-1a00-42af-acca-f262bd47bf93)
![Screenshot from 2024-08-07 12-29-07](https://github.com/user-attachments/assets/da317e7b-7cfd-4f1d-b2c0-f1fc77b354f7)
