### ISSUE TITLE
Not Seeing editor in custom fields

### ISSUE THREAD

**Issue by HarjasSodhi** [nshenderov/strapi-plugin-ckeditor#156]
I installed the library and its working by replacing the default rich text editor in strapi. Not seeing the ckeditor option in custom fields like shown in the screenshots in documentation. are the screenshots not valid anymore?

**Comment by nshenderov** [comment]
@HarjasSodhi Please follow the [issue template](https://raw.githubusercontent.com/nshenderov/strapi-plugin-ckeditor/master/.github/ISSUE_TEMPLATE/🪲-bug-report.md).
