### ISSUE TITLE
Custom config causing Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by stillhartkonzept** [nshenderov/strapi-plugin-ckeditor#160]
**Describe the bug**
Example ckeditor.js does not work for me. I tried copying the example code in the first ckeditor.js in the documentation and I got console error "Uncaught SyntaxError: Unexpected token ':'" and strapi failed to compile. I tried changing the name of the file to ckeditor.txt and strapi ran, but my new config wasn't visible. I required the code in https://github.com/nshenderov/strapi-plugin-ckeditor/issues/127#issuecomment-1916364219 AND a file called ckeditor.txt for my new config to work. 
I'm running strapi 4.25.9 using node 18. 

**To Reproduce**
1. Install a new version of strapi
2. Install the ckeditor plugin
3. copy the example text in the documentation at https://github.com/nshenderov/strapi-plugin-ckeditor into ckeditor.js
4. run develop

**Expected behavior**
The config that's documented by the example becomes available as "My Custom Preset"
What actually happened: I got "Uncaught SyntaxError: Unexpected token ':'" and strapi failed to run.

**please complete the following information:**
 - plugins.js (if exist)
 module.exports = () => ({});
 - package.json
 {
  "name": "gta",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "deploy": "strapi deploy"
  },
  "devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.1.3",
    "@strapi/plugin-cloud": "4.25.9",
    "@strapi/plugin-graphql": "^4.25.9",
    "@strapi/plugin-i18n": "4.25.9",
    "@strapi/plugin-users-permissions": "4.25.9",
    "@strapi/strapi": "4.25.9",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "strapi-plugin-navigation": "^2.5.3",
    "styled-components": "5.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "6e813ed3-8cb0-4483-96c2-b02cffeb0b21"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

 - node version
 18.0.0

**Comment by MichaelG-Dev** [comment]
Hello, I had the same problem recently. To fix it, I changed the format of the CKEConfig() function.
I pretty much put presets into an object (it being the "configuration" object) and returned it.
```
const CKEConfig = () => {
    return {
        presets: {
        myCustomPreset: {
            field: {...},
            editorConfig:{
                plugins: [...],
                toolbar: [...],
                heading: {...},
                image: {...},
                table: {...}
            }
        }
    }
}}```

**Comment by nshenderov** [comment]
There is a typo in the example, I forgot to include the parentheses
