### ISSUE TITLE
"Open in a new tab" toggle does not update html source

### ISSUE THREAD

**Issue by inc00ming** [nshenderov/strapi-plugin-ckeditor#163]
**Describe the bug**
When using **Open in a new tab** toggle does not update html source
**To Reproduce**
1. Type a word and select all word and click Link button on the editor
2. Disable "**Open in a new tab**"
3. Check html source
4. Source shows `target="_blank"`

**Expected behavior**
Source should have `target="_self"`

**Screenshots**
![Screenshot from 2024-09-27 10-12-57](https://github.com/user-attachments/assets/07fcd0af-bff3-440a-9bc7-76ca81c6090f)

![Screenshot from 2024-09-27 10-13-09](https://github.com/user-attachments/assets/a49f6c90-a78c-4d6d-8903-66d59d85c89e)

**please complete the following information:**
 - plugins.js (if exist)
 - package.json
     - ```"@_sh/strapi-plugin-ckeditor": "^2.1.0",```
 - node version
     - Node 18 

**Additional context**

**Comment by nshenderov** [comment]
@inc00ming
I see the issue. CKEditor doesn't add target="_self" by default either. I'll look into how it can be resolved. In the meantime, you can customize the link configuration in your config file to fit your needs.
