### ISSUE TITLE
When add images from Media Library, it won't add the selected images after clicking on Finish button.

### ISSUE THREAD

**Issue by XavierTian** [nshenderov/strapi-plugin-ckeditor#165]
**Describe the bug**
When add images from Media Library, it won't add the selected images after clicking on Finish button.

**To Reproduce**
1. Go to 'Content Manager'
2. Click on any types of Content Type
3. Go to CKEditor and click on "Media Library"
4. Select an image, then click on "Finish" button. 
5. See error

**Expected behavior**
It should be able to add the image to where the cursor is in CKEditor.

**Screenshots**
![image issue](https://github.com/user-attachments/assets/b9f95d86-3425-46b0-93d2-c0d3d74fb90e)

**Comment by nshenderov** [comment]
@XavierTian 
Which version of Strapi and the plugin are you currently using?
