### ISSUE TITLE
Strapi V5: field label is not updated after using 'Configure the view'

### ISSUE THREAD

**Issue by g-u-x** [nshenderov/strapi-plugin-ckeditor#166]
**Describe the bug**
When using the CKEditor as a custom field, I’m trying to edit the label with “Configure the view”, however it’s still showing the native label used when the field was created.
Not 100% sure, but it may be related to the issue #161.

**To Reproduce**
1. Create a Content-Type and add CKEditor as a custom field, name it “textField” as identifier attribute (where no spaces are allowed)
2. Once created, go to “Configure the view“ and edit the field label to “Text Field”.
3. You’ll see that the field is still showing “textField” as label.

**Expected behavior**
The field label should be updated after editing with “Configure the view” option.
It works fine on Strapi native fields.

**Screenshots**
<img width="811" alt="IssueA" src="https://github.com/user-attachments/assets/0ace69f0-5106-4aa8-b30a-b3347e493714">
<img width="615" alt="IssueB" src="https://github.com/user-attachments/assets/45864921-3a8c-47c6-930a-d0dee33a007b">

**please complete the following information:**
```
{
  "name": "strapi",
  "version": "0.1.0",
  "private": true,
  "description": "A Strapi application",
  "scripts": {
    "build": "strapi build",
    "deploy": "strapi deploy",
    "develop": "strapi develop",
    "start": "strapi start",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^4.0.4",
    "@strapi/plugin-cloud": "5.0.0",
    "@strapi/plugin-graphql": "^5.0.0",
    "@strapi/plugin-users-permissions": "5.0.0",
    "@strapi/provider-upload-aws-s3": "^5.0.0",
    "@strapi/strapi": "5.0.0",
    "mysql2": "3.9.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "d9aef491-642d-48b6-9c88-7192b4091523"
  }
}
```

Node v18.18.0

**Comment by nshenderov** [comment]
Will try to figure out how it works in Strapi v5 since I can't find a proper migration guide for custom field plugins yet
