### ISSUE TITLE
Returned html not seems right

### ISSUE THREAD

**Issue by hieuhuynhstraits** [nshenderov/strapi-plugin-ckeditor#169]
hi, im facing an issue which is some component such as Table, Code block, or quote,...etc does not contain styling html code but only raw text. Look at the image below:

In this image you can see table contain border

<img width="146" alt="image" src="https://github.com/user-attachments/assets/6f2534e2-fede-4688-afab-08d399b7c62d">

But the result (which i call from api) does not contain them 

> <figure class="table">
    <table>
        <tbody>
            <tr>
                <td>
                    1
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    3
                </td>
                <td>
                    4
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    5
                </td>
            </tr>
            <tr>
                <td>
                    6
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</figure>
<p>
    &nbsp;
</p>

so this is a bug or do i have to do some customization? If so, then how ?

**Comment by nshenderov** [comment]
Hi, this isn't a bug. You need to style it on your frontend. Check out the guide here: https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/css.html#styling-the-published-content

**Comment by hieuhuynhstraits** [comment]
Im kind of new to strapi and also not familiar with html, can you guide me in more detail like: after installing the plugin what do i have to do (go to Directory A, find some file, edit it, etc....)

**Comment by hieuhuynhstraits** [comment]
> Hi, this isn't a bug. You need to style it on your frontend. Check out the guide here: https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/css.html#styling-the-published-content

So you mean i can only style it on my FE side but not server side to make the value contain styling?

**Comment by nshenderov** [comment]
I'd suggest you to ask for help in the discord community or explore some guides online

**Comment by nshenderov** [comment]
Looks like this issue is no longer relevant
