### ISSUE TITLE
How to Add Custom Styled Block Elements to CKEditor plugin

### ISSUE THREAD

**Issue by olegyahont15** [nshenderov/strapi-plugin-ckeditor#174]
Hello, strapi-plugin-ckeditor team!

I'm using the CKEditor plugin in the Strapi admin panel and would like to add custom-styled blocks. Could you please guide me on how to define and add custom block styles that will appear in the "Styles" dropdown menu for CKEditor?

I want to add my own styles with specific formatting options for things like highlights, alerts, and notes. If there are any particular files or configurations where these styles should be defined, I’d appreciate the details.

Thank you in advance for your help!

![Screenshot_1](https://github.com/user-attachments/assets/40fa90c2-55a3-4651-8487-fbb0d0ed06a7)

**Comment by nshenderov** [comment]
@olegyahont15
Follow the configuration guide https://github.com/nshenderov/strapi-plugin-ckeditor#configuration
This feature is called Style https://ckeditor.com/docs/ckeditor5/latest/features/style.html
Here’s one way to configure it:

```js
const CKEConfig = () => ({
  presets: {
    default: {
      styles: `
        .ck-content p.custom-callout {
            --border-color: #7b79ff;
            padding: 1.2em 2em;
            border: 1px solid var(--border-color);
            border-left: 10px solid var(--border-color);
            background: #181826;
            border-radius: 5px;
            margin: 1.5em 2em;
            box-shadow: 5px 5px 0 #10101a;
            font-family: var(--ck-georgia-serif-font-stack);
            font-size: 20px;
            font-weight: bold;
            color: #d1d1d1;
        }
      `,
      editorConfig: {
        style: {
          definitions: [
            {
              name: "Custom Callout",
              element: "p",
              classes: ["custom-callout"],
            },
          ],
        },
      },
    },
   },
});
```
