### ISSUE TITLE
How could I add styles for the alignment of inserted images?

### ISSUE THREAD

**Issue by ulmetum** [nshenderov/strapi-plugin-ckeditor#176]
Hi. 

I'm using strapi-plugin-ckeditor and would like to be able to add custom styles to inserted images using custom classes or something like that.

Regards.

**Comment by nshenderov** [comment]
Hi, no issues with that, you're good to go, check out the [configuration guide](https://github.com/nshenderov/strapi-plugin-ckeditor?tab=readme-ov-file#%EF%B8%8F-configuration) and CKEditor 5 docs for more details.
