### ISSUE TITLE
[3.0.7] Two richtext-fields on same level crush Media Lib assets inserting

### ISSUE THREAD

**Issue by lxndrrud** [nshenderov/strapi-plugin-ckeditor#177]
**Describe the bug**
First of all, thank you for the plugin, progress from version 2 to 3 is huge.

Two richtext-fields on same level crush Media Lib assets inserting.

**To Reproduce**
1. Create component with two richtext fields.
2. Try adding any asset from Media Lib (video insert is bugging too) to first richtext field.
3. Media asset will jump to another richtext field (even to another component if it will not be minified in edit view).

**Expected behavior**
Asset will be added to first richtext field.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/355ddad5-6a77-4b2e-92c7-4489d04bc1b1)
![изображение](https://github.com/user-attachments/assets/234fab55-299e-4d5e-ba73-1d284ddbe1fa)
![изображение](https://github.com/user-attachments/assets/eadc4267-add0-4b51-af22-311d14d54b08)

**please complete the following information:**
 - plugins.js (if exist)
 - ckeditor.js (if exist): in repo file is named ckeditor.js
[ckeditor.js.txt](https://github.com/user-attachments/files/17660548/ckeditor.js.txt)

 - package.json
 "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^3.0.7",
    "@notum-cz/strapi-plugin-content-versioning": "^1.2.6",
    "@retikolo/drag-drop-content-types": "^1.5.0",
    "@strapi/plugin-graphql": "4.15.5",
    "@strapi/plugin-i18n": "4.15.5",
    "@strapi/plugin-users-permissions": "4.15.5",
    "@strapi/provider-email-nodemailer": "^4.6.1",
    "@strapi/provider-upload-aws-s3": "4.15.5",
    "@strapi/strapi": "4.15.5",
    "canvas": "^2.11.2",
    "dotenv": "^16.4.5",
    "knex": "^3.1.0",
    "pdfmake": "^0.2.8",
    "pg": "^8.8.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^5.2.0",
    "react-select": "^5.8.0",
    "sharp": "^0.33.5",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^2.16.5",
    "@graphql-codegen/fragment-matcher": "^3.2.0",
    "@graphql-codegen/schema-ast": "^2.4.0",
    "@graphql-codegen/typescript": "^2.4.1",
    "@graphql-codegen/typescript-operations": "^2.2.1",
    "@types/koa": "^2.15.0"
  }
 - node version - 18.20.4

**Additional context**
There is no such a bug in version 2. There is something in field editor identification where HTML inserting is happening.

**Comment by nshenderov** [comment]
Hey, it was fixed in [3.0.8](https://github.com/nshenderov/strapi-plugin-ckeditor/releases/tag/v3.0.8)

**Comment by lxndrrud** [comment]
Thank you, mr. nshenderov!)
