### ISSUE TITLE
Gallery feature

### ISSUE THREAD

**Issue by trustechadmin** [nshenderov/strapi-plugin-ckeditor#178]
Hi,

do you have any idea, how I could add a gallery feature to the editor? I would love to have a gallery feature like in wordpress, where user can add multiple galleries through the content. Thank you!

**Comment by nshenderov** [comment]
Hi,

You could use the style feature or write a plugin to handle that, it’s essentially a block of images. However, it might be better to place all image-related content into separate Strapi components so you can optimize it and render independently on your frontend, whether as a gallery, slider, or something else.
