### ISSUE TITLE
how to add a fullsreen and preview button?

### ISSUE THREAD

**Issue by Nasi2000** [nshenderov/strapi-plugin-ckeditor#179]
I would really like to enlarge the editor area using the fullscreen button and to be able to preview the article. Are there such functions or will it be possible to add them?

**Comment by nshenderov** [comment]
It can be achieved through a custom plugin, though this feature isn't officially provided. I don't have plans to develop it at the moment. There's actually a community plugin called ckeditor5-fullscreen that was part of v1 of this plugin. You can try it out, but as I recall, it didn't work well, so I eventually removed it.

**Comment by nshenderov** [comment]
@Nasi2000 Actually, I checked again the current state of this feature and available community plugins and decided to implement it. It will be available soon and will work similarly to the default Strapi editor.

![Screenshot from 2024-11-17 21-06-41](https://github.com/user-attachments/assets/ab5b2d3f-ec83-4c28-9c07-81211fa74ef4)

**Comment by nshenderov** [comment]
[Release v5](https://github.com/nshenderov/strapi-plugin-ckeditor/commit/f4bd05f3c04146abfd952356238b321c520b8e23)
