### ISSUE TITLE
Can we create patch over the existing ckeditor plugin?

### ISSUE THREAD

**Issue by CharuGoyalS** [nshenderov/strapi-plugin-ckeditor#181]

**Comment by nshenderov** [comment]
Can you elaborate?

**Comment by CharuGoyalS** [comment]
- I want to modify the CKEditor plugin so that all MS Office file extensions open in a new tab using https://view.officeapps.live.com/op/view.aspx.

The challenge is that the CKEditor distribution files in node_modules (the dist folder) are dynamically generated each time we install the plugin. This prevents a consistent patch from being created and applied, as the contents change.

**Comment by nshenderov** [comment]
You can clone the repo and modify it locally. However, if I understand correctly, you want to modify links. Have you checked the https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-attributes-to-links-based-on-predefined-rules-automatic-decorators ?
