### ISSUE TITLE
Render Content in React App

### ISSUE THREAD

**Issue by fxmb** [nshenderov/strapi-plugin-ckeditor#182]
How are people actually rendering the result from the strapi endpoint from the editor in their apps? I just get a plain HTML string? Is there not a way to parse this more securely and inject styles for certain html tags (e.g. p is always rendered in a predefined way)?

It feels incredibly buggy to convert and parse something like this that comes as a string from the strapi api:

```
'<p>Paragrpah test </p><h1>Test H1</h1><h2>Test H2</h2><figure class="image"><img src="http://localhost:1337/uploads/image_8c4144f113.png" alt="image.png" srcset="http://localhost:1337/uploads/thumbnail_image_8c4144f113.png 245w, http://localhost:1337/uploads/small_image_8c4144f113.png 500w, http://localhost:1337/uploads/medium_image_8c4144f113.png 750w, http://localhost:1337/uploads/large_image_8c4144f113.png 1000w" sizes="100vw" width="1000"></figure><p>&nbsp;</p>'
```

How come there is nothing about this anyways?

Why can I not query the editor and receive json blocks that I can iterate over and manipulate easily? Now the only way to render this I see is to use some hacky `dangerouslySetInnerHtml` tag somewhere in my app.

What am I missing here? Thanks for any support and pointers

In Editor.js (unfortunately deprecated), you would just receive an array of JSON objects that you could render with their React Component and pass your own styling for each tag....

**Comment by nshenderov** [comment]
> How are people actually rendering the result from the strapi endpoint from the editor in their apps? I just get a plain HTML string?

People typically render HTML strings in their apps the usual way. You can google examples if you're unsure how to do this.

> Is there not a way to parse this more securely and inject styles for certain html tags (e.g. p is always rendered in a predefined way)?

Its not a good idea to parse it, but if you really need to, you can use some libraries for it.

> It feels incredibly buggy to convert and parse something like this that comes as a string from the strapi api

Why do you need to convert and parse it at all? HTML output is meant to be rendered as-is in most cases.

> Why can I not query the editor and receive json blocks that I can iterate over and manipulate easily?

This editor produces HTML/Markdown, which is saved as a string in the database. It's not designed to produce JSON blocks.

> Now the only way to render this I see is to use some hacky dangerouslySetInnerHtml tag somewhere in my app.
What am I missing here? Thanks for any support and pointers
In Editor.js (unfortunately deprecated), you would just receive an array of JSON objects that you could render with their React Component and pass your own styling for each tag....

If you prefer structured JSON output, why not use the default Strapi rich text editor? It does exactly what you're looking for.
