### ISSUE TITLE
Adding a math plugin results in duplicate CKEditor error.

### ISSUE THREAD

**Issue by tshmieldev** [nshenderov/strapi-plugin-ckeditor#185]
// app.tsx
import '@wiris/mathtype-ckeditor5';

// ckeditor.ts

plugins: [
                globalThis.Mathematics,
                ...
                
I know there are similar issues on github, I tried the advice but I still can't make it work.
I have tried this plugin, and ckeditor5-math

**Comment by tshmieldev** [comment]
I have changed the import, as suggested in the issue you referenced.
Now, I don't get that error, but when I add this to the ckeditor.ts config:
plugins: [
                globalThis.MathType,
                ...

Strapi compiles the admin, but when I open the editor, it keeps loading indefinitely, and the console has some new errors:
<img width="492" alt="image" src="https://github.com/user-attachments/assets/944b92f2-ddec-4a06-bb52-27c2f21e3731">

<img width="503" alt="image" src="https://github.com/user-attachments/assets/53cc274c-0a8f-4460-8b84-4f5f9955a38b">

**Comment by nshenderov** [comment]
I don’t see any types provided by the plugin, so of course ts doesn't see it.
What do you mean by "it's not there"? Naturally, you need to add buttons to the toolbar and address security policies since this plugin loads scripts, styles, and images.

![image](https://github.com/user-attachments/assets/079d0b10-43e9-4358-92da-de4f875920ce)

**Comment by tshmieldev** [comment]
I thought all I need to do is import it and pass it in plugins: []
What you have in the screenshot is exactly what I need, how did you accomplish it please

**Comment by nshenderov** [comment]
app.tsx
```js
import MathType from '@wiris/mathtype-ckeditor5/dist/browser/index.js';
globalThis.MathType = MathType;
```
ckeditor.ts
```js
plugins: [
  globalThis.Mathematics,
  ...
],
toolbar: [
  'MathType',
  'ChemType',
  ...
]
```

**Comment by tshmieldev** [comment]
Thank you so much, I get the buttons now, yet when I click them they don't do anything. I haven't added the security policies, I don't know what they should be, could you please send them here?

<img width="490" alt="image" src="https://github.com/user-attachments/assets/e3210da6-392c-4bf6-b73f-25aa25084f68">

**Comment by tshmieldev** [comment]
I added the correct security config. The plugin loads, the css is bugged (the popup is hidden behind sidebar etc). I think I can just handle that with some css.

I still get this error though

**Comment by tshmieldev** [comment]
It is worse than that, the popup "works" - all the buttons in it work, you can input into it just fine, but the CKEditor field doesn't get what you input in the popup...

**Comment by nshenderov** [comment]
These errors aren’t related to this repository. It would be better to report them to the maintainers of the plugin.

**Comment by tshmieldev** [comment]
Okay, I will, thanks

Can you confirm that it also doesn't work for you?

**Comment by nshenderov** [comment]
There is a comment in the related issue mentioning similar behavior, I just checked that plugin loads and that's it.

**Comment by tshmieldev** [comment]
Okay thanks
