### ISSUE TITLE
CK Editor keeps loading after upgrade to v4.0.11 in Strapi v5 migration

### ISSUE THREAD

**Issue by lookeswong** [nshenderov/strapi-plugin-ckeditor#186]
After upgrading to Strapi v5 and CKEditor 4.0.11, I'm encountering an issue where the editor fails to load completely.

I am getting these error in my browser console

hook.js:608 Warning: Received `false` for a non-boolean attribute `unique`.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'editorConfig')

<img width="704" alt="image" src="https://github.com/user-attachments/assets/130dcb7d-1d8a-461e-8aac-18174e9f3a00">

 how do I resolve this?

**Comment by nshenderov** [comment]
Provide more details, your ckeditor.js, plugins.js, the version you're migrating from, and any other relevant information that could help pinpoint the issue. Most likely, the problem lies in your configuration file.

**Comment by lookeswong** [comment]
Hi @nshenderov, thanks for your response!

I am updating from v2.1.1 to v4.0.11. After investigating the documentation, I realized the issue was due to the 'toolbar' preset in my JSON file like below.

`"editor": {
      "type": "customField",
      "options": {
          "preset": "toolbar"
      },
      "customField": "plugin::ckeditor5.CKEditor"
  },`
  
  Once I updated the preset field to "default", its working fine now
  `"editor": {
      "type": "customField",
      "options": {
          **"preset": "default"**
      },
      "customField": "plugin::ckeditor5.CKEditor"
  },`
