### ISSUE TITLE
How to strip enclosing <p> tag from response?

### ISSUE THREAD

**Issue by TestyTestyTestyTesty** [nshenderov/strapi-plugin-ckeditor#187]
Hey.
Is it possible to set up the config of CKEditor so it doesn't enclose content in p the  tag?
Or is it something that I need to solve on the frontend side of the app?
If possible to solve on the config side, what needs to be done?
Screenshot for reference:
![image](https://github.com/user-attachments/assets/c412acd2-5aa3-40ec-9636-3fc30f74008a)

**Comment by nshenderov** [comment]
You can find the answer in the official ckeditor team's repo. In short - no. This issue isn't directly related to this plugin or its config file but to ckeditor itself.
