### ISSUE TITLE
in plugins.js > Ckeditor > config I need to have support for div container

### ISSUE THREAD

**Issue by tdserviceco** [nshenderov/strapi-plugin-ckeditor#2]
How do I add support to add div container in source mode? its frustrating to get it deleted everytime I go away from source mode.

**Comment by nshenderov** [comment]
@tdserviceco You can cofigure "General HTML Support" plugin for that, look at https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html

I think about include something like this in the next update https://github.com/centaur54dev/ckeditor5-custom-element

**Comment by tdserviceco** [comment]
I found what i need: htmlSupport: {
    allow: [
        {
            name: /.*/,
            attributes: true,
            classes: true,
            styles: true
        }
    ]
} but I cant for dear life of me understand where to put the plugin? is it plugin: {GeneralHtmlSupport} or how? and how do I import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';? I keep getting Cannot use import statement outside a module

**Comment by nshenderov** [comment]
The plugin is already built in, all you have to do something like:
```js
ckeditor:{
  enabled: true,
  config:{
     editor:{ // editor default config
      // .... 
      htmlSupport: {
          allow: [
              // Enables plain <div> elements.
              {
                  name: 'div'
              },
      
              // Enables plain <div>, <section> and <article> elements.
              {
                  name: /^(div|section|article)$/
              },
      
              // Enables <div>s with all inline styles (but no other attributes).
              {
                  name: 'div',
                  styles: true
              },
      
              // Enables <div>s with foo and bar classes.
              {
                  name: 'div',
                  classes: [ 'foo', 'bar' ]
              },
      
              // Adds support for `foo` and `bar` classes to the already supported
              // <p> elements (those are enabled by the dedicated paragraph feature).
              {
                  name: 'p',
                  classes: [ 'foo', 'bar' ]
              },
      
              // Enables <div>s with foo="true" attribute and bar attribute that
              // can accept any value (boolean `true` value works as an asterisk).
              {
                  name: 'div',
                  attributes: {
                      foo: 'true',
                      bar: true
                  }
              },
      
              // Adds support for style="color: *" to the already supported
              // <p> and <h2-h4> elements.
              {
                  name: `/^(p|h[2-4])$/'`,
                  styles: { 'color': true }
              },
          ]
      }
    }
  }
}
```
and be careful with that:
```js
htmlSupport: {
    allow: [
        {
            name: /.*/,
            attributes: true,
            classes: true,
            styles: true
        }
    ]
}
```
because it may not work

**Comment by tdserviceco** [comment]
Ah thanks will play around with this :) thanks

**Comment by tdserviceco** [comment]
hmmm doesnt seem to work with only htmlSupport: {
        allow: [
          // Enables plain <div>, <section> and <article> elements.
          {
            name: 'div',
          }
        ]
      } can you try to see if you get a div back?

**Comment by nshenderov** [comment]
I have tested it and it works, try to copy all from my comment above, also you can add:

```js
heading: {
      options: [
              {
              model: 'div3',
              view: {name: 'div', classes: 'ck-heading_h3_b'}, title: 'div (border)', class: 'ck-heading_heading3', converterPriority: 'high'
              }
       ]
}
```

**Comment by tdserviceco** [comment]
Im so sorry, I got it to work now.. you're right.. I needed to copy the entire thing you send me.. now I can do my DIV with class and give it a name :)

Thanks for your patient.. I sometime cant understand these setup.

**Comment by nshenderov** [comment]
You are welcome!
