### ISSUE TITLE
Using this ckeditor inside react app (but still upload to strapi media library)

### ISSUE THREAD

**Issue by sonyafung** [nshenderov/strapi-plugin-ckeditor#20]
Hi,

I was wondering if there was a way to use this build of the CKEDITOR inside my react app, but still be able to upload images into the strapi media library, just inside react app, which is connected to the strapi CMS database. 

Is this possible to do that, or would I have to create my own plugin that is totally separate from this?

I really just want to be able to use this ckeditor build in my react app too, not just with the default rich text wysywyg in strapi cms, and be able to upload images directly to the strapi media library like this plugin allows. This all worked in version 3 of strapi, but since migrating to version 4, the react custom ckeditor I used to have no longer works. 

Can someone point me in the right direction? I was asking about this in the strapi discord, and they suggested I had to build my own plugin from scratch.

**Comment by nshenderov** [comment]
@sonyafung Hi,
This plugin was made specially for strapi. For another react app you have to do your own build of ckeditor with a custom upload plugin. You can take some code from another builds or plugins for ckeditor on github. My suggest is to start from [ckeditor5 react docs](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/react.html) with [ckeditor5 custom upload udapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) and [strapi upload plugin docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration).

**Comment by sonyafung** [comment]
@nshenderov Can I ask, does the image library button for the strapi media library come within a custom builder of the ckeditor, or did you have to create that specific button from scratch? I can't find an "image library" folder in the custom ckeditor builder that connect to strapi. That's why I opened this issue. Do I have to make that from scratch?

**Comment by nshenderov** [comment]
@sonyafung This button is a simple [ckeditor button](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin.html) that toggles MediaLib inside strapi. You can find some code for this here https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg. But I dont understand how do you plan to use the strapi medialib outside strapi.

**Comment by sonyafung** [comment]
@nshenderov Thank you, I think that's all I need in order to build this same version of the ckeditor inside my react app. 

Just to clarify, my react app folder is inside the strapi CMS, so the react-app is a sub-directory inside strapi. That's why I want the wysiwyg inside the react-app, a sub folder of Strapi CMS, to be able to use the same ckeditor to upload images to the strapi media library.
