### ISSUE TITLE
Adding Custom Plugin

### ISSUE THREAD

**Issue by damreywil** [nshenderov/strapi-plugin-ckeditor#25]
Sorry I could not find any information anywhere else about how to go about adding ckeditor plugins to this setup.

What is the suggested and/or best way to go about adding additional custom ckeditor plugins to this strapi plugin? (i.e. add toolbar button to trigger simple plugin)

Any information would be greatly appreciated.

Thanks in advance.

**Comment by darmanovic** [comment]
I'm also lookin for this feature.

As far as I know, you need to build your own CK editor from it's source plus dependencies this strapi plugin uses (strapi upload plugin, etc)

**Comment by joeyboth** [comment]
Me too, I want the footnotes plugin.

**Comment by nshenderov** [comment]
Currently there is no way of adding additional plugins in this build. As @darmanovic said you need to build your own build of ckeditor for this and paste your build into this plugin.

Some links that may help:
https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/react.html
https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html
https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/package-generator.html
https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html

**Comment by darmanovic** [comment]
@nshenderov
Sorry for going off topic, but In rough terms what would be easiest way to add responsive columns capability, or inserting predefined custom HTML element at button click? At the moment i'm writing custom HTML by hand, but that would be unacceptable for the end non technical user.

**Comment by nshenderov** [comment]
@darmanovic 
You can use headings with custom css class for this. Check this:
https://ckeditor.com/docs/ckeditor5/latest/features/headings.html
https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html
But I prefer to use strapi components for complicated html
