### ISSUE TITLE
Error compiling with Strapi 4.3.3

### ISSUE THREAD

**Issue by andrespaucar** [nshenderov/strapi-plugin-ckeditor#26]
how can i solve this error
when I do "npm run build" it compiles normally, but when I do "npm start" I get that error 
![image](https://user-images.githubusercontent.com/35370608/183971657-78a85965-1921-4e01-a776-dfa2709245c4.png)

I need help thanks

**Comment by nshenderov** [comment]
@andrespaucar Check #23
