### ISSUE TITLE
Question, MediaEmbed providers

### ISSUE THREAD

**Issue by sijokun** [nshenderov/strapi-plugin-ckeditor#28]
MediaEmbed only adds 

```
<figure class="media">
     <oembed url="...."></oembed>
</figure>

```
I want him to add an iframe for youtube. 

```
editor:{
  mediaEmbed: {
    providers: [
      {
        name: 'youtube',
        url: [
          /^(?:m\.)?youtube\.com\/watch\?v=([\w-]+)(?:&t=(\d+))?/,
          /^(?:m\.)?youtube\.com\/v\/([\w-]+)(?:\?t=(\d+))?/,
          /^youtube\.com\/embed\/([\w-]+)(?:\?start=(\d+))?/,
          /^youtu\.be\/([\w-]+)(?:\?t=(\d+))?/
        ],
        html: match => {
          const id = match[ 1 ];
          const time = match[ 2 ];

          return (
            '<div class="youtube-embed" style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;">' +
              `<iframe src="https://www.youtube.com/embed/${ id }${ time ? `?start=${ time }` : '' }" ` +
                'style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" ' +
                'frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>' +
              '</iframe>' +
            '</div>'
          );
        }
      }
    ]
  },
}
```

I tried to add youtube provider manually, but it does not work, what am I doing wrong?

**Comment by nshenderov** [comment]
@sijokun 
That will solve your problem
https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#including-previews-in-data:~:text=mediaEmbed.previewsInData%20to%20true

Regular expressions doesnt allowed in configuration because this config will transform to JSON format first before ckeditor will get it

**Comment by sijokun** [comment]
> @sijokun 
> That will solve your problem
> https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#including-previews-in-data:~:text=mediaEmbed.previewsInData%20to%20true
> 
> Regular expressions doesnt allowed in configuration because this config will transform to JSON format first before ckeditor will get it
> 
> 

Thx! How I can create custom provider for example for telegram if I can't use regex?

**Comment by nshenderov** [comment]
For now the only way is to write it in the plugin file itself https://github.com/nshenderov/strapi-plugin-ckeditor/blob/c7a892581dba0bafced0bfcb4106f7ec314376c3/admin/src/components/CKEditor/index.js#L101

**Comment by sijokun** [comment]
I think I found a problem, everything is shown correctly in the admin panel if you add your provider to the plugin code, but the client only has `<figure class="media"><oembed url="https://t.me/telegram/189"></oembed></figure>`
The ckeditor saves such a tag to the database and replaces it when displayed, but it sends the strapi directly from the database and does not replace it.

Do you have any ideas what to do with it?

**Comment by timraasveld** [comment]
I think this problem is because of two reasons:

- the editor config is converted to JSON, truncating the `html` callback and your regexes. Proposed solution in https://github.com/nshenderov/strapi-plugin-ckeditor/pull/54
- You have to tell mediaEmbed not to use oembed, otherwise it won't respect your `html`.
   ```js
      mediaEmbed: {
        previewsInData: true,
   ```
