### ISSUE TITLE
[strapi 4.3.3]  It works normally in development mode, but an error occurs after build.   

### ISSUE THREAD

**Issue by masaki22** [nshenderov/strapi-plugin-ckeditor#29]
In strapi version 4.1.11, it worked well in any situation. 

The version was upgraded to strapi 4.3.3 version. After that, it works fine in Develop mode, but if you proceed with the Start script after executing the Build command, the corresponding error occurs.

My environment is like this.
```
node version v16.15.1
"@_sh/strapi-plugin-ckeditor": "^1.1.2",
"@strapi/strapi": "4.3.3",
```

```
npm install 
npm run build
npm run start 
```

works fine

When I enter the Content Manager page, the editor doesn't work and throws that error.

```
Uncaught (in promise) TypeError: Property description must be an object: null
    at defineProperties (<anonymous>)
    at Ea._getConfig (main.8f200ec4.js:5:30318)
    at Ea.<anonymous> (main.8f200ec4.js:5:29268)
    at Generator.next (<anonymous>)
    at main.8f200ec4.js:1:644
    at new Promise (<anonymous>)
    at S0 (main.8f200ec4.js:1:464)
    at Ea._initializeEditor (main.8f200ec4.js:5:28866)
    at Ea.<anonymous> (main.8f200ec4.js:5:28553)
    at Generator.next (<anonymous>)

```

Isn't there some good way? I've tried to solve it on my own, but I can't seem to get it to work, so I'm asking for help.

**Comment by nshenderov** [comment]
@masaki22 Hi, looks like problem with security middleware after update or something with the database
