### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by joeyboth** [nshenderov/strapi-plugin-ckeditor#30]
Is it possible to add footnotes for the next release? This would really be a top feature addition.

**Comment by joaojoyce** [comment]
Hi! I need this plugin, too. 

There's [this CKEditor Footnote plugin](https://www.npmjs.com/package/ckeditor5-footnote), but I don't really know if it works.

I would happily contribute to this project if I could run this source code locally next to a clean Strapi installation, but I'm not sure how to do it.

@nshenderov, could you share with us how do you run your project locally next to a clean Strapi install?
Thank you for your work!

**Comment by nshenderov** [comment]
@joeyboth @joaojoyce Hi,
There is no official footnotes plugin for ckeditor 5 and no one good unofficial, you can try to make one by yourself or create an issue in the official github. Locally, I have custom ckeditor build and default strapi setup. If you want some plugin to be in this build I can add it.
[Plugin you mentioned](https://github.com/Precise-software/CKEditor5-footnote) looks abandoned.

**Comment by nshenderov** [comment]
#60
