### ISSUE TITLE
Are you sure you want to leave this page?

### ISSUE THREAD

**Issue by oioioiio** [nshenderov/strapi-plugin-ckeditor#31]
Hi. Thanks for the great plugin.

I've run into a minor issue on content types that feature a CK editor. To reproduce the issue:

1. Add or edit an entry that features a CK editor 
2. Don't make any changes to the content
3. Navigate to a different page

**What happens**
CK editor thinks that content has been modified and a browser alert asks 'Are you sure you want to leave this page?'

**What should happen**
If no content has been modified, it should be possible to navigate away without an alert.

Strapi version: v4.3.6
Node vserion: v14.20

**Comment by nshenderov** [comment]
I faced this bug when I was modifying collection types. Generally, all works fine, and the alert occurs when you do some changes to your collections in the content-type builder, if you save your entry after it it will continue to work fine. I'm not sure why it happens and what causes the issue but I presume that something from the hot-reload mechanism may cause it
