### ISSUE TITLE
How to pass own colors to color picker?

### ISSUE THREAD

**Issue by vhnizdiukh** [nshenderov/strapi-plugin-ckeditor#32]
Hello, I need to replace default colors of the color picker with my own colors. How can I do that?

![image](https://user-images.githubusercontent.com/81363137/190113781-e22e8b2c-a0ad-4d81-bf8a-f1e272cad3ff.png)

**Comment by nshenderov** [comment]
@vhnizdiukh https://ckeditor.com/docs/ckeditor5/latest/features/font.html#specifying-available-colors:~:text=%23-,Specifying%20available%20colors,fontColor.colors%20and%20config.fontBackgroundColor.colors%20configuration%20options%20to%20do%20so.,-ClassicEditor%0A%20%20%20%20.create

**Comment by Krak86** [comment]
@vhnizdiukh you can add just `fontColor `object with correct props.
Check payload [https://jsonblob.com/1030068658973720576](url)
