### ISSUE TITLE
How to add base url to images when we use GraphQL 

### ISSUE THREAD

**Issue by SudhakarPunniyakotti** [nshenderov/strapi-plugin-ckeditor#33]
While using GraphQL to get the JSON data the images are relative like /uploads/image.jpeg so how to add the base URL to images like https://server_url/uploads/imafe.jpeg? 

Thank you.

**Comment by nshenderov** [comment]
@SudhakarPunniyakotti Hi, https://github.com/nshenderov/strapi-plugin-ckeditor#:~:text=If%20you%20use%20default%20upload%20provider%20and%20you%20want%20prefix%20img%20url%20with%20api%20path%20you%20need%20to%20add%20baseURL%20in%20api.js%20file%20(config/api.js)

**Comment by yarikwest** [comment]
@nshenderov this doesn't work for me. Maybe I something messing?
