### ISSUE TITLE
I need help adding additional Special Characters

### ISSUE THREAD

**Issue by ghost** [nshenderov/strapi-plugin-ckeditor#34]
I am trying to add additional Special Characters. I am following this guide:

https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html

The setup is different in Strapi. When i define my function and try to call it in plugins.js I get a void message.

Does anyone know how to do this?

**Comment by nshenderov** [comment]
@mrossi-rankworks Hi, you cannot add directly new plugins/function in the build used in this plugin.
