### ISSUE TITLE
baseURL is not working

### ISSUE THREAD

**Issue by ajankowy035** [nshenderov/strapi-plugin-ckeditor#39]
Hi guys! I am currently working with strapi v4 and we have implemented this CKEditor which has great features. However I am facing a problem with this baseURL configuration which is not working properly IMO. Or I am doing something wrong. 
So I provided changes according to your documentation:
<img width="838" alt="Zrzut ekranu 2022-10-21 o 10 32 32" src="https://user-images.githubusercontent.com/78428488/197159739-29e5337a-ee5e-47fd-9aab-fb4118a0e1be.png">

My config/api.js
```
module.exports = ({ env }) => ({
  baseURL: env('PUBLIC_URL', 'http://localhost:1337'),
});
```
The result:

<img width="315" alt="Zrzut ekranu 2022-10-21 o 10 55 54" src="https://user-images.githubusercontent.com/78428488/197156074-9e1c3abb-992e-48f9-be71-a31a88e54903.png">

So after adding adding baseURL to config/api.js nothing is happening and sources for uploaded images inside text editor are not prefixed with provided URL.

Is there any possible solution for that issue?

**Comment by dannyrippon** [comment]
@ajankowy035 did you find a fix for this? Im also having issues

**Comment by ajankowy035** [comment]
no, I didn't find a fix for that. We found another way - using nginx on frontend - we created a redirection to the strapi app when it's calling /uploads

**Comment by hypong** [comment]
Does anyone know the solution to this?

**Comment by ajankowy035** [comment]
@hypong  Maybe you could try to transform the response with controller in strapi? [controllers](https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#adding-a-new-controller )

**Comment by jacobedawson** [comment]
If anyone is wondering, adding a "url" property to the module under server.js (./config/server.js) in the Strapi folder did the trick, here is what the config looks like:

```
module.exports = ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  url: env("PUBLIC_URL", "http://localhost:1337"), // <- ADDING THIS LINE TO THE CONFIG
  app: {
    keys: env.array("APP_KEYS"),
  },
});
```

I tried both methods, and adding the baseURL property to the .config/api.js file did nothing. You could use process.env in a ternary condition if you want to have the url adjusted based on the server environment.
