### ISSUE TITLE
Strapi build hangs

### ISSUE THREAD

**Issue by francescob** [nshenderov/strapi-plugin-ckeditor#4]
Hi, reporting a very strange issue here. When I add the plugin to my strapi installation, the build process get stuck at around 20% (sometimes is 21, other 22, never went past 23). No error reported, the process just hangs there, I've tried waiting more than 30 minutes with no success. Without the plugin the build process completes in less than a minute. 
The machine I'm trying to build is a MacBook air with the latest macOS, node version 16.15 (but I've tried version 14 as well), and strapi 4 at the latest version.

**Comment by nshenderov** [comment]
Hi, how your plugins.js looks like?

**Comment by philohelp** [comment]
I have the exact same error here, with a MacBook Pro.
Deps:
    "@_sh/strapi-plugin-ckeditor": "^1.1.0",
    "@strapi/plugin-i18n": "4.1.7",
    "@strapi/plugin-users-permissions": "4.1.7",
    "@strapi/provider-upload-cloudinary": "^4.1.7",
    "@strapi/strapi": "4.1.7",
    "pg": "8.6.0"

config/plugins:
module.exports = ({ env }) => {
  return {
    ckeditor: true,
    upload: {
      config: {
        provider: "cloudinary",
        providerOptions: {
          cloud_name: env("CLOUDINARY_NAME"),
          api_key: env("CLOUDINARY_KEY"),
          api_secret: env("CLOUDINARY_SECRET"),
        },
        actionOptions: {
          upload: {},
          delete: {},
        },
      },
    },
  };
};

**Comment by nshenderov** [comment]
@philohelp just tried on strapi 4.1.7 and catch the same issue as you, dont know exactly where is the problem, but on 4.1.8 and above everything works fine for me

![2022-05-20 014218](https://user-images.githubusercontent.com/103522779/169416203-d9936a39-0810-4013-9d87-c2e59f00ea1e.jpg)

**Comment by philohelp** [comment]
Thanks ! Upgraded to 4.1.8, it works nicely.
