### ISSUE TITLE
Deprecation warning: Usage of "size" prop in Stack component is deprecated. This is discouraged and will be removed in the next major release. Please use "spacing" instead

### ISSUE THREAD

**Issue by fuxianwei** [nshenderov/strapi-plugin-ckeditor#41]
The update prompt pops up on the console. Please check and upgrade the relevant properties
[https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-widget-toolbar-no-items](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-widget-toolbar-no-items)

<img width="852" alt="截屏2022-10-31 17 33 16" src="https://user-images.githubusercontent.com/1736689/198977043-f66bf956-a1f3-4799-829d-2cd30b8c9435.png">

**Comment by nshenderov** [comment]
@fuxianwei toolbar-no-items error says all itself, you didn't specify any one item in the toolbar array, and it looks like the prompt about the usage of the "size" property is not related to ckeditor
