### ISSUE TITLE
Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by distributeddev** [nshenderov/strapi-plugin-ckeditor#42]
I am getting following error in browser console and I cant see the preview in the editor when embedding videos 

```
Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

main.95e79f29.js:15982 Refused to frame 'https://player.vimeo.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

main.95e79f29.js:15982 Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

main.95e79f29.js:15982 Refused to frame 'https://player.vimeo.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

```

And this is what I see in browser

![Screenshot 2022-11-01 at 14 53 16](https://user-images.githubusercontent.com/107478866/199263255-37fad29e-a532-4404-810c-0526385ed7d0.png)

Following is my middlware.js in strapi.

```
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "default-src": [
            "'self'",
            "data:",
            "blob:",
            "res.cloudinary.com",
            "lh3.googleusercontent.com",
            "platform-lookaside.fbsbx.com",
            "dl.airtable.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],          
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "res.cloudinary.com",
            "lh3.googleusercontent.com",
            "platform-lookaside.fbsbx.com",
            "dl.airtable.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "res.cloudinary.com",
            "lh3.googleusercontent.com",
            "platform-lookaside.fbsbx.com",
            "dl.airtable.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          "frame-src": [
            "'self'",
            "data:",
            "blob:",
            "res.cloudinary.com",
            "lh3.googleusercontent.com",
            "platform-lookaside.fbsbx.com",
            "dl.airtable.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          "iframe-src": [
            "'self'",
            "data:",
            "blob:",
            "res.cloudinary.com",
            "lh3.googleusercontent.com",
            "platform-lookaside.fbsbx.com",
            "dl.airtable.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],          
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  {
    name: "strapi::cors",
    config: {
      enabled: true,
      headers: "*",
      origin: ["*"],
    },
  },
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

any idea?

**Comment by dannyrippon** [comment]
@distributeddev it looks like you have strapi::security twice. Just remove the second one above "strapi::cors"

**Comment by denvradiy** [comment]
I faced the same issue, did you find out how to fix this ?

**Comment by denvradiy** [comment]
Hi @distributeddev !

Here is my middlewares.js 

`module.exports = [
  'strapi::errors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',

  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "default-src": [
            "'self'",
            "data:",
            "blob:",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "s3.eu-west-1.amazonaws.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "s3.eu-west-1.amazonaws.com",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          "frame-src": [
            "'self'",
            "data:",
            "blob:",
            "https://www.youtube.com/",
            "https://www.youtube.com/embed/",
            "https://player.vimeo.com/",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: 'strapi::cors',
    config: {
      enabled: true,
      headers: '*',
      origin: ['*'],
    }
  }
];` 

It fixed the issue for me, try it!

**Comment by csharpee** [comment]
Awesome, this also worked for me! You rock and thank you for sharing. I was digging into my nginx CSP, but it looks like Strapi also has its own CSP.

**Comment by timraasveld** [comment]
> Also important to note, this plugin allows for **PREVIEWING** the embeded content, but the ` html attribute must be converted into proper HTML for the item to be displayed.
> 
> 😓
> 
> This plugin is useless unless you either:
> 
> 1. Pay embedly or iframely money
> 2. Program your own syntax to convert  attributes into an `<iframe>` template formatting.
> 
> the HTML syntax used.
> 
> ```
> <figure class="media"><oembed url="https://www.youtube.com/watch?v=bX_Ihr0"></oembed></figure>
> ```
> 
> For an example of 2., the actual code the `<oembed> `needs to be converted into from youtube.
> 
> ```
> <iframe width="560" height="315" src="https://www.youtube.com/embed/DvkQo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
> ```

To make the MediaEmbed plugin output an iframe that you can insert directly in your client app, add `previewsInData: true` in plugins.ts/.js:
```
ckeditor: {
  config: {
    ..
    editor: {
      ...
      mediaEmbed: {
        previewsInData: true
```
This results in the following HTML when pasting a YT video:
```html
<figure class="media">
    <div data-oembed-url="https://www.youtube.com/watch?v=TcbFFoAQ5Ck">
        <div style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;">
            <iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        </div>
    </div>
</figure>
```

**Comment by csharpee** [comment]
Sweet, I will give this a test the next time I get the chance.

**Comment by dinhkhanh** [comment]
I've added `previewsInData: true` but it still produces "semantic" data. 

My  `/config/plugins.ts`:

```
ckeditor5: {
    enabled: true,
    config: {
      editor: {
        mediaEmbed: {
          previewsInData: true
        }
      }
   }
},
```

Using `"@_sh/strapi-plugin-ckeditor": "^2.0.4",` version.

What did I do wrong? I've also try `/config/ckeditor.ts` version but still doesn't work.

**Comment by timraasveld** [comment]
> I've added `previewsInData: true` but it still produces "semantic" data.
> 
> My `/config/plugins.ts`:
> 
> ```
> ckeditor5: {
>     enabled: true,
>     config: {
>       editor: {
>         mediaEmbed: {
>           previewsInData: true
>         }
>       }
>    }
> },
> ```
> 
> Using `"@_sh/strapi-plugin-ckeditor": "^2.0.4",` version.
> 
> What did I do wrong? I've also try `/config/ckeditor.ts` and `/config/ckeditor.txt` but still doesn't work.

The answer I showed is for CKEditor 1.x.x. In 2.x.x, it seems you can only use /config/ckeditor.txt, which I have no experience with. I might be able to figure it out later when I have time to upgrade to 2.x.

**Comment by dinhkhanh** [comment]
> > I've added `previewsInData: true` but it still produces "semantic" data.
> 
> > 
> 
> > My `/config/plugins.ts`:
> 
> > 
> 
> > ```
> 
> > ckeditor5: {
> 
> >     enabled: true,
> 
> >     config: {
> 
> >       editor: {
> 
> >         mediaEmbed: {
> 
> >           previewsInData: true
> 
> >         }
> 
> >       }
> 
> >    }
> 
> > },
> 
> > ```
> 
> > 
> 
> > Using `"@_sh/strapi-plugin-ckeditor": "^2.0.4",` version.
> 
> > 
> 
> > What did I do wrong? I've also try `/config/ckeditor.ts` and `/config/ckeditor.txt` but still doesn't work.
> 
> 
> 
> The answer I showed is for CKEditor 1.x.x. In 2.x.x, it seems you can only use /config/ckeditor.txt, which I have no experience with. I might be able to figure it out later when I have time to upgrade to 2.x.

Found out that an typo error in the code base causes my issue, as I describe [here](https://github.com/nshenderov/strapi-plugin-ckeditor/issues/89)
