### ISSUE TITLE
Oembedly Plugin is Useful for Previews Only while editing; How-to disable this plugin?

### ISSUE THREAD

**Issue by csharpee** [nshenderov/strapi-plugin-ckeditor#47]
In relation to #42 

It is important to note, this plugin allows for **PREVIEWING** the embeded content, but the `<oembed></oembed> html attribute must be converted into proper HTML for the item to be displayed. 

:sweat: 

This plugin is useless unless you either: 

1. Pay embedly or iframely money
2. Program your own syntax to convert <oembed> attributes into an `<iframe>` template formatting. 

the HTML syntax used in Strapi CK5editor.
```
<figure class="media"><oembed url="https://www.youtube.com/watch?v=bX_Ihr0"></oembed></figure>
```
To display that syntax in HTML, we either use 1. a payed provider to convert it for us or 2. we program it our selves or 3. we require the author andor editor to copy / paste the video iframe directly from the website i.e. youtube.com. 

The actual code that is needed to display the video.
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/DvkQo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

How to disable this plugin?

**Comment by csharpee** [comment]
These two plugins should **not** be default. 
```
MediaEmbed,
MediaEmbedToolbar,
```

I tested this to disable them, but it didn't work. 
```
                        plugin: {

                                // disable oembed
                                removePlugins: ['MediaEmbedToolbar'],
                                removePlugins: ['MediaEmbed'],
                                removePlugins: ['PasteFromOffice'],
```

**Comment by csharpee** [comment]
Alright, I have figured it out. 
```
                        editor: { // editor default config

                                // https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html
                                // if you need markdown support and output set: removePlugins: [''],
                                removePlugins: ['PasteFromOffice','MediaEmbed','MediaEmbedToolbar'],
```

**Comment by timraasveld** [comment]
To make the MediaEmbed plugin output an iframe that you can insert directly in your client app, add the `previewsInData` in plugins.ts/.js:
```
ckeditor: {
  config: {
    ..
    editor: {
      ...
      mediaEmbed: {
        previewsInData: true
```
This results in the following HTML when pasting a YT video:
```html
<figure class="media">
    <div data-oembed-url="https://www.youtube.com/watch?v=TcbFFoAQ5Ck">
        <div style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;">
            <iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        </div>
    </div>
</figure>
```

**Comment by timraasveld** [comment]
Turns out non-JSON serializable fields, such as the `html` callback and regexes, are truncated when fetching the plugin config.

This is solved by allowing you to define your CKEditor config as a global `globalThis.ckEditorConfig` in `config/ckeditor.js` script in #54. Check out the PR for an example.

In case you need this fix before the PR is merged, use this version in your package.json `dependencies`
```
    "@_sh/strapi-plugin-ckeditor": "nshenderov/strapi-plugin-ckeditor#pull/54/head",
```

**Comment by DHFW** [comment]
I had to add the `mediaEmbed` object inside the `editorConfig` to make the ckeditor use the actual config. That was not clear to me...

Inside the CKEditor configuration:
```js
globalThis.CKEditorConfig = {
   ...
   editorConfig: {
      plugins: ...
      ...
      mediaEmbed: {
          previewsInData: true,
          providers: [
            {
             ...
   }
```
