### ISSUE TITLE
Feature Request: A save button while in full-screen

### ISSUE THREAD

**Issue by csharpee** [nshenderov/strapi-plugin-ckeditor#49]
A small feature request to be able to save ones work while in full-screen mode. 

The feature request would have a save button in top right or a floating button that isn't in the way for the author to focus on writing only. 

On saving the document, the full screen will exit and use the save feature already built into Strapi.

**Comment by nshenderov** [comment]
#60 There is no official fullscreen plugin for ckeditor5 and the fullscreen plugin that we have is not good enough I'm not planning to develop and maintain it so since v2 of this plugin, the fullscreen plugin isn't included in the build
