### ISSUE TITLE
maxLengthCharacters property without 'options.' prefix crashes admin panel

### ISSUE THREAD

**Issue by jmucio** [nshenderov/strapi-plugin-ckeditor#51]
I added this plugin and upgraded to Strapi v4.5.3.

The file `node_modules/@ckeditor/strapi-plugin-ckeditor/admin-src/index.js` contains a line which lists **maxLengthCharacters** as a value for a particular property. When you build your admin panel, Chrome shows an error:

`Uncaught (in promise) Invariant Violation: 'maxLengthCharacters' must be prefixed with 'options.'
    at t (http://localhost:1337/admin/main.a627abc1.js:572:555)
    at http://localhost:1337/admin/main.a627abc1.js:175:22198
    at Array.forEach (<anonymous>)
    at w.register (http://localhost:1337/admin/main.a627abc1.js:175:22145)
    at Object.register (http://localhost:1337/admin/main.a627abc1.js:181:33)
    at http://localhost:1337/admin/admin-app.4993638d.chunk.js:66:12701
    at Array.forEach (<anonymous>)
    at ar.<anonymous> (http://localhost:1337/admin/admin-app.4993638d.chunk.js:66:12670)
    at Generator.next (<anonymous>)
    at http://localhost:1337/admin/admin-app.4993638d.chunk.js:66:5295`

Prefixing this value with 'option.' in the appropriate main.js file fixes the problem. So, perhaps a change needs to be made somewhere in this plugin or how the build step handles this object during compilation?

**Comment by nshenderov** [comment]
@jmucio You messed up with repos you added another different plugin and here is its repo https://github.com/ckeditor/strapi-plugin-ckeditor

**Comment by jmucio** [comment]
@nshenderov Thanks! The v0.0.5 upgrade takes care of this issue.
