### ISSUE TITLE
Looking for Line Height option inside the toolbar 

### ISSUE THREAD

**Issue by irishikesh** [nshenderov/strapi-plugin-ckeditor#52]
I was seeking for a feature for line height. Are there any immediate intentions to include the same? Or let me know if there are any workarounds.

Although I looked at a few sources, they weren't helpful to me: https://ckeditor.com/cke4/addon/lineheight

**Comment by nshenderov** [comment]
@irishikesh #60 Since v2 of this plugin you can include your own plugins. There is no official line height plugin for ckeditor 5 and I've not planned to do one so you can create one or explore some existing and include it to your config
