### ISSUE TITLE
How can we wrap images with text on left side

### ISSUE THREAD

**Issue by kavinsharma** [nshenderov/strapi-plugin-ckeditor#53]
Hi Team, i am trying to align image on left side in rich text editor but there is no such option available in image toolbar.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/22246774/210183464-3dab2d9a-a12b-4bd8-aa8d-493f64ced6ae.png">

**Comment by Denis2222** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html#presentational-styles

I try to add "imageStyle:alignLeft" and "imageStyle:alignRight" in 
ckeditor:
> config:
> > editor:
> > >image:
> > > >toolbar.

But not working, after a strapi build nothing change.
Maybe need to rebuild plugin ?
