### ISSUE TITLE
forcePasteAsPlainText: true does not work

### ISSUE THREAD

**Issue by Przemek625** [nshenderov/strapi-plugin-ckeditor#56]
How to enable forcePasteAsPlainText: true in configuration of this plugin?

**Comment by nshenderov** [comment]
@Przemek625 https://ckeditor.com/docs/ckeditor5/latest/updating/migration-from-ckeditor-4.html#configuration-options-compatibility-table:~:text=N/A.%20No%20longer%20needed%20as%20CKEditor%205%20removes%20all%20unwanted%20markup%20that%20cannot%20be%20edited%20with%20the%20enabled%20editor%20plugins.


https://github.com/nshenderov/strapi-plugin-ckeditor#%EF%B8%8F-configuration

**Comment by Przemek625** [comment]
It looks that is is enabled by default. But it works only when I execute "ctr + shift +v"(copy as plain text), but for normal paste(ctr +v) is always paste formatted text. Do you know how to force this plugin to paste ALWAYS unformatted text?

**Comment by nshenderov** [comment]
@Przemek625 Read the documentation, there is a separate plugin for pasting text into the editor https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-plain-text.html
About "paste ALWAYS unformatted text" looks like there isn't such an option available, you can open an issue in ckeditor's repo

**Comment by wai15985** [comment]
@nshenderov CKEditor 5 offers a function for that – plainTextToHtml(), is it possible to implement?
