### ISSUE TITLE
Default Config on Readme has hebrew as default Language

### ISSUE THREAD

**Issue by meganoob1337** [nshenderov/strapi-plugin-ckeditor#61]
![image](https://user-images.githubusercontent.com/5018646/214842870-64d0b89d-a8cc-4526-acc9-1dbbada21fb6.png)

The default Language in the Readme should probably be 'en' :)

**Comment by nshenderov** [comment]
This is an example of creating your own custom config, 'he' is there just to clarify that you can specify any language you want. 
e.g You can have a few editors one will change content based on i18n and another one will be always in rtl ignoring i18n but still having different values for different locales

**Comment by meganoob1337** [comment]
Okay, i just used it as a Template and wanted to get started with that config, and it confused the hell out of me :D
