### ISSUE TITLE
ckeditor.txt not loaded for typescript project

### ISSUE THREAD

**Issue by viandika** [nshenderov/strapi-plugin-ckeditor#64]
I'm trying the v2.0.0 of the plugin on strapi v4.5.6 with typescript. I have tried putting copying the example from readme to `/config/ckeditor.txt` but it doesn't get picked up. I checked the debugger on the browser and found that the injected script is `'globalThis.CKEditorConfig = null'`.

Based on the source code, if it is typescript project, it tries to read from the `/dist` folder. But when building the strapi project, it would not copy/compile `ckeditor.txt` file because it isn't a typescript file.

https://github.com/nshenderov/strapi-plugin-ckeditor/blob/e782475f54b8a50a04f55275c89ef5bf61a15745/server/services/config.js#L10-L19

If I change the line to ``const filename = `${appDir}/config/ckeditor.txt`;``, it works as intended. Is there additional configs I need to do for the `ckeditor.txt` file to be copied during build or should we just remove the isTSProject condition?

**Comment by nshenderov** [comment]
Yeah, I missed that, it probably will be better to remove these isTSProject and jsDir variables and remain only appDir than invent a way to copy that config to the dist directory, since usually, the whole app folder is included and even the config folder isn't excluded.
