### ISSUE TITLE
Instaaltion Error 

### ISSUE THREAD

**Issue by manishionc** [nshenderov/strapi-plugin-ckeditor#69]
Hello I am trying to install and replace the default rich text with CKeditor I Installed it with NPM but it's not showing in Strapi 
Please help me.
Thank you

**Comment by manishionc** [comment]
> > 
> 
> This plugin is custom field. Go to content type builder, select or create new content type, when modifying or creating new fileds choose "Custom", there will be option for ckeditor 5. Of course for this to work you have to install plugin first and **rebuild** your application.

Thankyou found it

**Comment by Bradzer** [comment]
> > 
> 
> This plugin is custom field. Go to content type builder, select or create new content type, when modifying or creating new fileds choose "Custom", there will be option for ckeditor 5. Of course for this to work you have to install plugin first and **rebuild** your application.

@nshenderov 
It would be a good thing to make this appear in the README.
