### ISSUE TITLE
Markdown support ?

### ISSUE THREAD

**Issue by SirJager** [nshenderov/strapi-plugin-ckeditor#7]
How can i enable markdown support ?

**Comment by nshenderov** [comment]
![2022-05-18 061534](https://user-images.githubusercontent.com/103522779/168949977-17b4cebd-5c2d-4b88-8677-07fc132c2f24.jpg)

```js
config:{
        plugin:{
        },
        editor:{
           removePlugins: [''],
        }
}
```
also read this https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html

**Comment by DevTrong** [comment]
Emptying the `removePlugins` helped.
I just saw that `tables` ain't working

It generates HTML output for tables:
![image](https://user-images.githubusercontent.com/3624351/169977569-aadeb5df-ac19-479f-9224-6e8aded01c8e.png)

I just checked CKEditor doc for markdown and the table seems to work there:
https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html
