### ISSUE TITLE
How to use ckeditor5 plugins?

### ISSUE THREAD

**Issue by milad2golnia** [nshenderov/strapi-plugin-ckeditor#71]
I'm still unable to figure out how can I add third-party plugins of ckeditor5 to this package.

I want to add [latex](https://www.npmjs.com/package/ckeditor5-latex) or [math](https://github.com/isaul32/ckeditor5-math) package, How can I add them?

NOTE: Also there is no `your-app/src/admin/app.js` file in typescript project.

**Comment by nshenderov** [comment]
@milad2golnia This plugin is based on dll build you can read about it here https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html
It seems like those plugins you mention don't use it so for example you can try to build a plugin locally and use produced dll build inside your project or ask an author of the plugin to make a build.
There is src/admin/app.tsx in a typescript project
