### ISSUE TITLE
Image url broken when I integrate with strapi-provider-upload-google-cloud-storage

### ISSUE THREAD

**Issue by ahsetiaki** [nshenderov/strapi-plugin-ckeditor#72]
Hi @nshenderov, first of all, thanks for the great work.

I create a Strapi app, deploy it into Google Cloud Run and store the images/media to Google Cloud Storage by integrating [@strapi-community/strapi-provider-upload-google-cloud-storage](https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage) plugin.

For image that I uploaded into image field, I got no problem. But when I upload image inside CKEditor, the image failed to be rendered

![Screenshot 2023-02-12 at 13 11 27 (1)](https://user-images.githubusercontent.com/70776044/218296422-64afb4a2-c68c-4093-8c7a-04fe824e01c0.jpg)

I tried to save it and when I check the url on get detail response. I got different url

```
{
     "thumbnail_img":  {
          "url":   "https://storage.googleapis.com/{redacted bucket}/cat.jpeg"   
     },
     "content": "...  <img src=\"https://{redacted domain}https://storage.googleapis.com/{redacted bucket}/cat.jpeg\" ... > ..."
}
```

I am aware this is because:

- CKEditor5 using ``url`` field on ``/config/server.ts`` to generate image url 
- [@strapi-community/strapi-provider-upload-google-cloud-storage](https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage) seems to replace ``/uploads/cat.jpeg`` into  ``https://storage.googleapis.com/{redacted bucket}/cat.jpeg``

How I can remove the prefix ``url`` from generated url so I can use only the url that generated by [@strapi-community/strapi-provider-upload-google-cloud-storage](https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage)?

Thanks in advance for your response!

**Comment by nshenderov** [comment]
@ahsetiaki Hi,
It looks like you specified url field in the server.ts, if so then remove it, you don't need it unless you use local upload provider

**Comment by nshenderov** [comment]
@ahsetiaki Yeah, I missed it, that is a problem. We need a fix for that. For now, it always adds this prefix from server.js if it exists. I use strapi with docker and traefik so haven't faced this issue. I'm tired of it, they change their API like every month, previously it worked through baseurl in api.js.

**Comment by ovieokeh** [comment]
I've opened a PR #78 to fix this issue as it is also present when [@provider-upload-aws-s3](https://github.com/nshenderov/strapi-plugin-ckeditor/pull/@strapi/provider-upload-aws-s3) is configured.

**Comment by ahsetiaki** [comment]
@ovieokeh thank you very much for your PR! I think it can be released soon because my project is still on progress haha cc @nshenderov
