### ISSUE TITLE
How to integrate ckeditor5-fullscreen into ckeditor plugin

### ISSUE THREAD

**Issue by phongduybui** [nshenderov/strapi-plugin-ckeditor#74]
Hi,
Could you give me the guide/steps for integrate `Full Screen` feature into this plugin. I have seen you mentioned about package: [ckeditor5-fullscreen](https://github.com/leknoppix/ckeditor5-fullscreen). But I couldn't find a way to implement it. Could you help me. 
Btw, many thanks to team to implement good plugin for community usage.

**Comment by ovieokeh** [comment]
I'm not a member of the team but I had the same needs so I raised a PR to implement this #77. Hopefully it gets merged soon
