### ISSUE TITLE
ckeditor.txt doesn't affect toolbars and buttons

### ISSUE THREAD

**Issue by apopov-ces** [nshenderov/strapi-plugin-ckeditor#80]
**Describe the bug**

**To Reproduce**
1. Create strapi app: `npx create-strapi-app --ts --quickstart`
2. cd to created directory `cd my-strapi-app`
3. Install CKeditor plugin: `yarn @_sh/strapi-plugin-ckeditor`
4. Create `config/ckeditor.txt` and paste there content of https://github.com/nshenderov/strapi-plugin-ckeditor#configuration
5. Open strapi, create component with RichText field
6. Create collection type `page` with dynamic zone that contains RichText  component
7. Open "content manager", create Page with RichText component, ensure CKEditor instantiated on the new field
8. Stop strapi
9. Change `config/ckeditor.txt`, replace `toolbar`'s content (everywhere) with `["bold", "italic"]`
10. Start strapi
11. Reload page with rich text component editor

**Actual behavior**
CKeditor's toolbar is unchanged and contains full default set of buttons

**Expected behavior**
CKeditor contains only "bold" and "italic" buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/122587500/222473430-72748ae3-8193-428e-a51e-2595baa88940.png)

**please complete the following information:**
 - plugins.js (if exist)
```
does not exist
```
 - package.json
```
{
  "name": "my-strapi-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.3",
    "@strapi/plugin-i18n": "4.7.1",
    "@strapi/plugin-users-permissions": "4.7.1",
    "@strapi/strapi": "4.7.1",
    "better-sqlite3": "8.0.1"
  },
  "author": "A Strapi developer",
  "strapi": {
    "uuid": "cd8ef687-7817-422f-9828-7558e0fbe6e5"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT",
  "main": "index.js",
  "keywords": []
}
```
 - node version
```
v18.13.0
```

**Additional context**
Test repository: https://github.com/apopov-ces/strapi-ckeditor-plugin-config-issue

**Comment by StuDownie** [comment]
Had the same confusion setting this up! 

At step 5 above - in the component's basic settings: make sure you click the "Choose editor version" field and select "Custom version"

**Comment by apopov-ces** [comment]
Thank you for response @StuDownie but I am afraid I haven't field you mentioned:

Basic settings:
![image](https://user-images.githubusercontent.com/122587500/222532286-cd049244-cf7c-4d12-b572-c0cb08d9bed3.png)

Advanced settings:
![image](https://user-images.githubusercontent.com/122587500/222532350-dadbf428-4416-4f62-9a63-c5a21f4e27d1.png)

**Comment by StuDownie** [comment]
That's just the built-in rich text field. When you add a component, choose the "custom" tab at the right to see this custom component

<img width="846" alt="Screenshot 2023-03-02 at 20 28 20" src="https://user-images.githubusercontent.com/12409726/222544571-fee82f5f-9df3-401d-9734-133d4c276c0d.png">

**Comment by apopov-ces** [comment]
Thanks, but still nothing on the Custom tab. It is strange that when searching by "ck" it shown only "official" plugin. Anyhow, even if installed it (and it marked as "installed", after strapi restart nothing apears in Custom Tab.

![image](https://user-images.githubusercontent.com/122587500/222616877-0c3f30a6-73d5-499e-91d3-e7d9ede5f5d2.png)

![image](https://user-images.githubusercontent.com/122587500/222618361-6f99704f-ad55-4551-991a-d084a5f835d5.png)

**Comment by apopov-ces** [comment]
It looks like official plugin is more much less customizable, so it cannot be used in my case anyhow. It even doesn't support toolbar adjustements

**Comment by javadbat** [comment]
i have the same problem

**Comment by StuDownie** [comment]
That's the official plugin. 

Install the one for this repo instead (look for the green icon)  https://market.strapi.io/plugins/@_sh-strapi-plugin-ckeditor

It **IS** customisable.

**Comment by apopov-ces** [comment]
Ok, finally I able to make it works. It seems that something was related to my initial setup. Remove `node_modules`, unistalled packages related to my ckeditor experiments and it works. Steps (for new repo):

1. Create strapi app: `npx create-strapi-app --ts --quickstart .`
2. Install CKeditor plugin: `yarn @_sh/strapi-plugin-ckeditor
3. Create config/ckeditor.txt and paste there content of https://github.com/nshenderov/strapi-plugin-ckeditor#
4. Build plugin (crucial step): `yarn build` (after that it appears in custom components in Strapi)
6. Open strapi, create component, let's call it "MyRichText":
  - Click "add field"
  - Switch to "custom" tab, 
  - Choose "CKEditor 5"
![image](https://user-images.githubusercontent.com/122587500/223013991-1419e59c-a403-4c6f-89e9-ce8e2200e524.png)
  - Give a name to your field and choose correct editor setup
![image](https://user-images.githubusercontent.com/122587500/223014061-89e56b51-9ef1-4dfa-ac9f-063b06d49c4a.png)
  - Click "OK" and "Save"

Result: When adding data `content` field contains only defined buttons on the toolbar.
